import Head from 'next/head'
import Image from 'next/image'
import { useEffect, useState } from 'react'
import styles from '../styles/Home.module.css'

import GlitchedWriter, {
	wait,
	presets
} from 'glitched-writer'

let introText = [
  "21 • 09 • 2021",
  "Gear Up",
  "We'll be waiting for the worthy",
  "First To Win Is Elligible for P500 GCash Prize",
  "<span style='color: yellow;'>ICPEP BulSU</span> Presents",
  "The<span style='color: red;'> Enigma</span>",
  "<span style='color: red;'>THE ENIGMA</span>",
  "See you soon"
]

let logs_static = []

export default function Home() {

  async function testFetch(){
    let data = await fetch("/api/hello", {method: "POST"})
    let daja = await data.json()
    console.log(daja)
  }

  

  const [ logs, setLogs ] = useState([]);
  
  

  function glitchery(){

    function logString(string) {
      logs_static.push(string)
      setLogs([...logs_static])
      //Writer && Writer.write("")
    }

    let Writer = new GlitchedWriter("#output", {
      ...presets.terminal,
      letterize: true,
      html: true
    }, logString);

    (async function () {
      for(let l in introText){
          await wait(1500);
          await Writer.write(introText[l]);
          await Writer.write("");
      }
    })();
  }
  
  const date = new Date();

  useEffect(() => {
    testFetch()
    glitchery()
  }, [])

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className="wrapper">
          <div className="log" id="logs">
              {
                  logs.map((e,i) => <p className="logList" key={`logs_${i}`} dangerouslySetInnerHTML={{__html:e}}></p>)
              }
          </div>
          <pre><output id="output"></output><div className="user-input"><span className="incentive">&gt;&gt;</span><input type="text"/></div></pre>
        </div>
      </main>

    </div>
  )
}
